<?php

use App\Http\Controllers\Api\AclMatrixController;
use App\Http\Controllers\Api\Area\GovernorateController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\Expense\ExpenseCategoryController;
use App\Http\Controllers\Api\Expense\ExpenseController;
use App\Http\Controllers\Api\NotificationController;
use App\Http\Controllers\Api\Operations\MaterialController;
use App\Http\Controllers\Api\Operations\MaterialRequestController;
use App\Http\Controllers\Api\Operations\MaterialRequestItemController;
use App\Http\Controllers\Api\Operations\PickupRequestController;
use App\Http\Controllers\Api\Operations\VisitController;
use App\Http\Controllers\Api\Orders\ActivityLogController;
use App\Http\Controllers\Api\Orders\ClientReturnController;
use App\Http\Controllers\Api\Orders\ClientSettlementController;
use App\Http\Controllers\Api\Orders\DashboardOrderController;
use App\Http\Controllers\Api\Orders\OrderController;
use App\Http\Controllers\Api\Orders\ShipperCollectionController;
use App\Http\Controllers\Api\Orders\ShipperReturnController;
use App\Http\Controllers\Api\PermissionController;
use App\Http\Controllers\Api\Plan\PlanController;
use App\Http\Controllers\Api\RefusedReasonController;
use App\Http\Controllers\Api\RoleController;
use App\Http\Controllers\Api\SettingController;
use App\Http\Controllers\Api\ShippingContent\ContentController;
use App\Http\Controllers\Api\Users\ClientController;
use App\Http\Controllers\Api\Users\ProfileController;
use App\Http\Controllers\Api\Users\ShipperController;
use App\Http\Controllers\Api\Users\UserController;
use App\Http\Middleware\UpdateLoginSessionLastSeen;
use Illuminate\Support\Facades\Route;

Route::post('/login', [AuthController::class, 'login']);

Route::middleware(['auth:sanctum', UpdateLoginSessionLastSeen::class])->group(function (): void {
    Route::get('acl', [AclMatrixController::class, 'matrix']);
    Route::apiResource('expense-categories', ExpenseCategoryController::class);
    Route::apiResource('expenses', ExpenseController::class);
    Route::apiResource('clients', ClientController::class)->only(['index', 'show']);
    Route::get('profile', [ProfileController::class, 'show']);
    Route::patch('profile', [ProfileController::class, 'update']);
    Route::apiResource('contents', ContentController::class);
    Route::apiResource('shippers', ShipperController::class)->only(['index', 'show']);
    Route::apiResource('users', UserController::class);
    Route::apiResource('roles', RoleController::class);
    Route::apiResource('permissions', PermissionController::class)->only(['index', 'show']);
    Route::get('notifications', [NotificationController::class, 'index']);
    Route::patch('notifications/{notificationId}/read', [NotificationController::class, 'markAsRead']);
    Route::patch('notifications/read-all', [NotificationController::class, 'markAllAsRead']);
    Route::apiResource('refused-reasons', RefusedReasonController::class);
    Route::get('settings', [SettingController::class, 'index']);
    Route::put('settings', [SettingController::class, 'update']);
    Route::apiResource('governorates', GovernorateController::class);
    Route::apiResource('plans', PlanController::class);
    Route::apiResource('materials', MaterialController::class);
    Route::apiResource('material-requests', MaterialRequestController::class);
    Route::apiResource('material-request-items', MaterialRequestItemController::class);
    Route::apiResource('pickup-requests', PickupRequestController::class);
    Route::apiResource('visits', VisitController::class);
    Route::post('orders/scan', [OrderController::class, 'scan']);
    Route::get('orders/my-orders', [OrderController::class, 'myOrders']);
    Route::patch('orders/bulk-change-status', [OrderController::class, 'bulkChangeStatus']);
    Route::patch('orders/bulk-change-shipper', [OrderController::class, 'bulkChangeShipper']);
    Route::patch('orders/{order}/change-status', [OrderController::class, 'changeStatus']);
    Route::patch('orders/{order}/change-shipper', [OrderController::class, 'changeShipper']);
    Route::patch('orders/{order}/change-note', [OrderController::class, 'changeNote']);
    Route::patch('orders/{order}/change-external-code', [OrderController::class, 'changeExternalCode']);
    Route::get('orders/{order}/history', [OrderController::class, 'history']);
    Route::get('orders/{order}/shipping-label', [OrderController::class, 'shippingLabel']);
    Route::get('dashboard/orders', [DashboardOrderController::class, 'summary']);
    Route::apiResource('orders', OrderController::class);
    Route::get('shipper-collections/eligible-orders', [ShipperCollectionController::class, 'eligibleOrders']);
    Route::patch('shipper-collections/{shipperCollection}/approve', [ShipperCollectionController::class, 'approve']);
    Route::patch('shipper-collections/{shipperCollection}/reject', [ShipperCollectionController::class, 'reject']);
    Route::apiResource('shipper-collections', ShipperCollectionController::class);
    Route::get('shipper-returns/eligible-orders', [ShipperReturnController::class, 'eligibleOrders']);
    Route::patch('shipper-returns/{shipperReturn}/approve', [ShipperReturnController::class, 'approve']);
    Route::patch('shipper-returns/{shipperReturn}/reject', [ShipperReturnController::class, 'reject']);
    Route::apiResource('shipper-returns', ShipperReturnController::class);
    Route::get('client-settlements/eligible-orders', [ClientSettlementController::class, 'eligibleOrders']);
    Route::patch('client-settlements/{clientSettlement}/approve', [ClientSettlementController::class, 'approve']);
    Route::patch('client-settlements/{clientSettlement}/reject', [ClientSettlementController::class, 'reject']);
    Route::apiResource('client-settlements', ClientSettlementController::class);
    Route::get('client-returns/eligible-orders', [ClientReturnController::class, 'eligibleOrders']);
    Route::patch('client-returns/{clientReturn}/approve', [ClientReturnController::class, 'approve']);
    Route::patch('client-returns/{clientReturn}/reject', [ClientReturnController::class, 'reject']);
    Route::apiResource('client-returns', ClientReturnController::class);
    Route::apiResource('activity-logs', ActivityLogController::class)->only(['index', 'show']);
});
